### PR TITLE
correct examples in documentation: typo/layout + math issue

### PR DESCRIPTION
**Pull request by jgmbenoit**
Description: upstream: correct examples in documentation: math
 Testing the package itself against the samples given in the documentation
 with the help of ExtractExamples (section 5.4 in GAPDoc Reference Manual)
 exhibits an unexpected `return', at least for blind eyes. We observe
 ```
 gap> J:=IdealAffineToricVariety([[1,0],[3,4]]);
 <two-sided ideal in Rationals[x_1,x_2,x_3,x_4,x_5], (3 generators)>
 gap> GeneratorsOfIdeal(J);
 [ -x_4^4+x_1, -x_4^3+x_2, -x_4^2+1 ]
 ```
 while we expect
 ```
 gap> J:=IdealAffineToricVariety([[1,0],[3,4]]);
 [ two-sided ideal in PolynomialRing(..., [ x_1, x_2 ]), (3 generators) ]
 gap> GeneratorsOfIdeal(J);
 [ -x_2^2+x_1, -x_2^3+x_1^2, -x_2^4+x_1^3 ]
 ```
 As pointed out by the upstream maintainer [private communication], the article
 "Computing with toric varieties'' in "Journal of Symbolic Computation"
 volume 42 issue 5 (May 2007, pages 511-532) [doi:10.1016/j.jsc.2006.08.005]
 uses this example as illustration (example 2.18 (b) p 520). At the time of
 patching, it is not clear neither to the upstream maintainer nor to the
 package maintainer whether or not the two answers are equivalent. Further
 investigations are on their ways.
 
 Meanwhile, to not introduce a faulty correction, the example is replaced by
 its sibling (example 2.18 (a) p 520) whose the expected and observed final
 answers are the same:
 ```
 gap> J:=IdealAffineToricVariety([[0,1],[2,-1]]);
 <two-sided ideal in Rationals[x_1,x_2,x_3], (1 generators)>
 gap> GeneratorsOfIdeal(J);
 [ -x_2^2+x_1 ]
 ```
 Note that this test failure might hide a serious bug.
Origin: vendor, Debian
Author: Jerome Benoit <calculus@rezozer.net>
Last-Update: 2016-12-28

### CODE REVIEW

**Comment by fingolfin** [comment]
I reformatted the issue to make it more readable.

**Comment by olexandr-konovalov** [comment]
I don't want to merge this PR at least for now and mask an existing issue #3. We need to investigate #3 first. Ideally, I'd like to have both examples in Toric tests (and maybe more from that JSC paper), to ensure that we regularly run tests and check their reproducibility.

**Comment by jgmbenoit** [comment]
On my side, as Debian maintainer, I will keep it until the issue is fully resolved. My aim here is to check the Debian package at build time and at install time, and eventually to have a consistent documentation.

**Comment by fingolfin** [comment]
We just replaced the content of this repository with a new one, which has a more comprehensive history. This breaks this PR -- sorry for that. But we are not likely to merge it at this point anyway.

**Comment by fingolfin** [comment]
Oops, I did not intend to close this (I must have misclicked), and now I cannot reopen :-(

**Comment by olexandr-konovalov** [comment]
@fingolfin I can't reopen it either :(

**Pull request closed without merging**
